info:
  app:
    name: uh2c gateway service application
    description: Microservice Zuul pour uh2c

# hide null json property 
jackson:
   default-property-inclusion: NON_NULL

# config hystrix zuul
hystrix:
 threadpool:
  default:
    coreSize: 1000
    maximumSize: 10000
    queueSizeRejectionThreshold: -1
    maxQueueSize: -1
    
  command:
    default:
      execution: 
        isolation:
          thread:
           timeoutInMilliseconds: 9000000
          
# config ribbon zuul
ribbon:
  ConnectTimeout: 9000000
  ReadTimeout: 9000000

# Feign config
feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000
  
# zuul routes use the service ids registered in Eureka
zuul:
  host:
    connect-timeout-millis: 9000000
    socket-timeout-millis: 9000000
  routes:
    compte-api:
      path: /uh2c/compte-api/**
      service-id: uh2c-gestion-compte-service
      sensitive-headers: Cookie,Set-Cookie
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1       

# profil DEV
---
spring:
  profiles: dev
  
# the gateway is a Eureka client but is not registered as a Eureka instance
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

# port server
server:
  port: 9090
